swipe:
  3: 
    left: 
    #  command: 'xdotool key alt+Right'
      sendkey: 'FORWARD'
    right: 
    #  command: 'xdotool key alt+Left'
      sendkey: 'BACK'
    up: 
    #  command: 'xdotool key super'
      sendkey: 'LEFTMETA'
    down: 
    #  command: 'xdotool key super'
      sendkey: 'LEFTMETA'
  4:
    left: 
      workspace: 'next'
    #  command: 'xdotool key ctrl+alt+Down'
    right: 
    #  command: 'xdotool key ctrl+alt+Up'
      workspace: 'prev'
    up: 
    #  command: 'xdotool key ctrl+alt+Down'
      workspace: 'next'
    down: 
    #  command: 'xdotool key ctrl+alt+Up'
      workspace: 'prev'
pinch:
  in:
    command: 'xdotool keydown ctrl click 4 keyup ctrl'
  out:
    command: 'xdotool keydown ctrl click 5 keyup ctrl'
